"""add document conversations

Revision ID: bc578604bcb4
Revises: ae96fb7d14d7
Create Date: 2026-07-26 01:39:57.953906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc578604bcb4'
down_revision: Union[str, Sequence[str], None] = 'ae96fb7d14d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_conversations_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_conversations_organization_id'), ['organization_id'], unique=False)

    op.create_table('document_conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['document_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_conversation_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_conversation_messages_conversation_id'))

    op.drop_table('document_conversation_messages')
    with op.batch_alter_table('document_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_conversations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_document_conversations_created_by_user_id'))

    op.drop_table('document_conversations')
    # ### end Alembic commands ###
